import type { CommodityKey } from "@/app/data";

export type CommoditySitePoint = {
  id: string;
  name: string;
  country: string;
  kind: "mine" | "field" | "belt" | "basin" | "terminal";
  lat: number;
  lon: number;
  note?: string;
  sourceUrl?: string;
};

export const commoditySiteDefaultSources: Record<CommodityKey, string> = {
  soybean: "https://www.fao.org/faostat/",
  wheat: "https://www.fao.org/faostat/",
  corn: "https://www.fao.org/faostat/",
  coffee: "https://www.fao.org/faostat/",
  cocoa: "https://www.fao.org/faostat/",
  sugar: "https://www.fao.org/faostat/",
  cotton: "https://www.fao.org/faostat/",
  soybeanOil: "https://www.fao.org/faostat/",
  oil: "https://www.eia.gov/international/",
  brent: "https://www.nstauthority.co.uk/data-centre/",
  naturalGas: "https://www.eia.gov/international/",
  aluminum: "https://www.usgs.gov/centers/national-minerals-information-center/aluminum-statistics-and-information",
  copper: "https://www.usgs.gov/centers/national-minerals-information-center/copper-statistics-and-information",
  nickel: "https://www.usgs.gov/centers/national-minerals-information-center/nickel-statistics-and-information",
  zinc: "https://www.usgs.gov/centers/national-minerals-information-center/zinc-statistics-and-information",
  lead: "https://www.usgs.gov/centers/national-minerals-information-center/lead-statistics-and-information",
  tin: "https://www.usgs.gov/centers/national-minerals-information-center/tin-statistics-and-information",
  cobalt: "https://www.usgs.gov/centers/national-minerals-information-center/cobalt-statistics-and-information",
  lithium: "https://www.usgs.gov/centers/national-minerals-information-center/lithium-statistics-and-information",
  gallium: "https://www.usgs.gov/centers/national-minerals-information-center/gallium-statistics-and-information",
  germanium: "https://www.usgs.gov/centers/national-minerals-information-center/germanium-statistics-and-information",
  gold: "https://www.usgs.gov/centers/national-minerals-information-center/gold-statistics-and-information",
  silver: "https://www.usgs.gov/centers/national-minerals-information-center/silver-statistics-and-information",
};

export const commoditySitePoints: Record<CommodityKey, CommoditySitePoint[]> = {
  soybean: [
    { id: "soy-mato-grosso", name: "Mato Grosso Belt", country: "Brazil", kind: "belt", lat: -12.5, lon: -55.5 },
    { id: "soy-midwest", name: "US Midwest Belt", country: "United States", kind: "belt", lat: 41.8, lon: -93.5 },
    { id: "soy-pampas", name: "Pampas Core", country: "Argentina", kind: "belt", lat: -33.1, lon: -61.0 },
    { id: "soy-heilongjiang", name: "Heilongjiang Belt", country: "China", kind: "belt", lat: 46.0, lon: 127.0 },
  ],
  wheat: [
    { id: "wheat-kansas", name: "Kansas Wheat Belt", country: "United States", kind: "belt", lat: 38.5, lon: -98.0 },
    { id: "wheat-black-sea", name: "Black Sea Wheat Belt", country: "Russia", kind: "belt", lat: 47.3, lon: 38.8 },
    { id: "wheat-prairie", name: "Canadian Prairies", country: "Canada", kind: "belt", lat: 52.1, lon: -106.7 },
    { id: "wheat-wa", name: "WA Wheatbelt", country: "Australia", kind: "belt", lat: -31.9, lon: 116.0 },
  ],
  corn: [
    { id: "corn-us", name: "US Corn Belt", country: "United States", kind: "belt", lat: 41.7, lon: -93.6 },
    { id: "corn-mato", name: "Mato Grosso Safrinha", country: "Brazil", kind: "belt", lat: -13.0, lon: -56.0 },
    { id: "corn-arg", name: "Cordoba Core", country: "Argentina", kind: "belt", lat: -31.4, lon: -64.2 },
    { id: "corn-jilin", name: "Jilin Corn Area", country: "China", kind: "belt", lat: 43.9, lon: 125.3 },
  ],
  coffee: [
    { id: "coffee-minas", name: "Minas Gerais", country: "Brazil", kind: "belt", lat: -18.5, lon: -46.5 },
    { id: "coffee-daklak", name: "Dak Lak", country: "Vietnam", kind: "belt", lat: 12.7, lon: 108.2 },
    { id: "coffee-antioquia", name: "Antioquia Zone", country: "Colombia", kind: "belt", lat: 6.2, lon: -75.6 },
    { id: "coffee-sidama", name: "Sidama", country: "Ethiopia", kind: "belt", lat: 6.9, lon: 38.4 },
  ],
  cocoa: [
    { id: "cocoa-civ", name: "Cote d'Ivoire Belt", country: "Cote d'Ivoire", kind: "belt", lat: 7.5, lon: -5.6 },
    { id: "cocoa-ghana", name: "Ashanti Belt", country: "Ghana", kind: "belt", lat: 6.7, lon: -1.6 },
    { id: "cocoa-ecuador", name: "Guayas Zone", country: "Ecuador", kind: "belt", lat: -2.1, lon: -79.9 },
    { id: "cocoa-sulawesi", name: "Sulawesi Cocoa Area", country: "Indonesia", kind: "belt", lat: -2.5, lon: 120.0 },
  ],
  sugar: [
    { id: "sugar-ribeirao", name: "Ribeirao Preto", country: "Brazil", kind: "belt", lat: -21.2, lon: -47.8 },
    { id: "sugar-up", name: "Uttar Pradesh Belt", country: "India", kind: "belt", lat: 26.8, lon: 80.9 },
    { id: "sugar-th", name: "Korat Sugar Area", country: "Thailand", kind: "belt", lat: 15.0, lon: 102.1 },
    { id: "sugar-fr", name: "Champagne Beet Area", country: "France", kind: "belt", lat: 49.2, lon: 4.0 },
  ],
  cotton: [
    { id: "cotton-tx", name: "Texas High Plains", country: "United States", kind: "belt", lat: 33.6, lon: -101.8 },
    { id: "cotton-gujarat", name: "Gujarat Belt", country: "India", kind: "belt", lat: 23.0, lon: 72.6 },
    { id: "cotton-xinjiang", name: "Xinjiang Belt", country: "China", kind: "belt", lat: 43.8, lon: 87.6 },
    { id: "cotton-mt", name: "Mato Grosso Cotton", country: "Brazil", kind: "belt", lat: -16.5, lon: -54.6 },
  ],
  soybeanOil: [
    { id: "soyoil-rosario", name: "Rosario Crushing Hub", country: "Argentina", kind: "terminal", lat: -32.95, lon: -60.66 },
    { id: "soyoil-mato", name: "Mato Grosso Feedstock", country: "Brazil", kind: "belt", lat: -12.5, lon: -55.5 },
    { id: "soyoil-iowa", name: "Midwest Crushers", country: "United States", kind: "belt", lat: 41.8, lon: -93.6 },
    { id: "soyoil-cofco", name: "Coastal Crushing Zone", country: "China", kind: "terminal", lat: 31.2, lon: 121.5 },
  ],
  oil: [
    { id: "oil-ghawar", name: "Ghawar Field", country: "Saudi Arabia", kind: "field", lat: 25.2, lon: 49.3 },
    { id: "oil-permian", name: "Permian Basin", country: "United States", kind: "basin", lat: 32.0, lon: -102.0 },
    { id: "oil-rumaila", name: "Rumaila Field", country: "Iraq", kind: "field", lat: 30.4, lon: 47.5 },
    { id: "oil-kashagan", name: "Kashagan Field", country: "Kazakhstan", kind: "field", lat: 46.2, lon: 52.2 },
    { id: "oil-burgan", name: "Burgan Field", country: "Kuwait", kind: "field", lat: 29.0, lon: 47.9 },
    { id: "oil-safaniya", name: "Safaniya Field", country: "Saudi Arabia", kind: "field", lat: 28.0, lon: 48.8 },
    { id: "oil-zakum", name: "Zakum Field", country: "UAE", kind: "field", lat: 25.0, lon: 52.6 },
    { id: "oil-kirkuk", name: "Kirkuk Field", country: "Iraq", kind: "field", lat: 35.47, lon: 44.39 },
    { id: "oil-santos", name: "Santos Basin", country: "Brazil", kind: "basin", lat: -25.0, lon: -43.5 },
    { id: "oil-bonny", name: "Niger Delta Hub", country: "Nigeria", kind: "terminal", lat: 4.42, lon: 7.17 },
    { id: "oil-canada-oilsands", name: "Athabasca Oil Sands", country: "Canada", kind: "basin", lat: 57.1, lon: -111.5 },
    { id: "oil-bakken", name: "Bakken Formation", country: "United States", kind: "basin", lat: 47.7, lon: -103.6 },
    { id: "oil-eagle-ford", name: "Eagle Ford Shale", country: "United States", kind: "basin", lat: 28.8, lon: -98.3 },
    { id: "oil-gom", name: "Gulf of Mexico Deepwater", country: "United States", kind: "field", lat: 27.5, lon: -90.0 },
    { id: "oil-orinoco", name: "Orinoco Belt", country: "Venezuela", kind: "belt", lat: 8.9, lon: -64.6 },
    { id: "oil-campos", name: "Campos Basin", country: "Brazil", kind: "basin", lat: -22.7, lon: -40.5 },
    { id: "oil-guyana", name: "Stabroek Block", country: "Guyana", kind: "field", lat: 6.8, lon: -57.8 },
    { id: "oil-ekofisk", name: "Ekofisk Field", country: "Norway", kind: "field", lat: 56.5, lon: 3.2 },
    { id: "oil-forties", name: "Forties Field", country: "UK", kind: "field", lat: 57.8, lon: 1.7 },
    { id: "oil-khazzan", name: "Khazzan Field", country: "Oman", kind: "field", lat: 22.6, lon: 57.2 },
    { id: "oil-kharg", name: "Kharg Export Terminal", country: "Iran", kind: "terminal", lat: 29.27, lon: 50.33 },
    { id: "oil-basra", name: "Basra Oil Terminal", country: "Iraq", kind: "terminal", lat: 29.8, lon: 48.8 },
    { id: "oil-abu-safah", name: "Abu Safah Offshore", country: "Saudi Arabia", kind: "field", lat: 26.9, lon: 50.3 },
    { id: "oil-kuwait-mina", name: "Mina al-Ahmadi", country: "Kuwait", kind: "terminal", lat: 29.08, lon: 48.14 },
    { id: "oil-libya-sirte", name: "Sirte Basin", country: "Libya", kind: "basin", lat: 29.8, lon: 18.0 },
    { id: "oil-algeria-hassi", name: "Hassi Messaoud", country: "Algeria", kind: "field", lat: 31.65, lon: 6.07 },
    { id: "oil-angola-block17", name: "Angola Block 17", country: "Angola", kind: "field", lat: -8.3, lon: 12.5 },
    { id: "oil-azeri-chirag", name: "Azeri-Chirag-Gunashli", country: "Azerbaijan", kind: "field", lat: 40.2, lon: 51.1 },
    { id: "oil-sakhalin-1", name: "Sakhalin-1", country: "Russia", kind: "field", lat: 52.9, lon: 143.1 },
    { id: "oil-vankor", name: "Vankor Cluster", country: "Russia", kind: "field", lat: 67.0, lon: 82.0 },
    { id: "oil-daqing", name: "Daqing Field", country: "China", kind: "field", lat: 46.6, lon: 125.1 },
    { id: "oil-bohai", name: "Bohai Offshore", country: "China", kind: "field", lat: 38.7, lon: 120.3 },
    { id: "oil-bombay-high", name: "Mumbai High", country: "India", kind: "field", lat: 19.3, lon: 72.2 },
    { id: "oil-malaya", name: "Malay Basin", country: "Malaysia", kind: "basin", lat: 6.0, lon: 104.5 },
    { id: "oil-nws", name: "North West Shelf", country: "Australia", kind: "field", lat: -19.6, lon: 116.6 },
    { id: "oil-otway", name: "Otway Basin", country: "Australia", kind: "basin", lat: -39.0, lon: 142.0 },
  ],
  brent: [
    { id: "brent-core", name: "Brent Field", country: "UK", kind: "field", lat: 61.0, lon: 1.7 },
    { id: "brent-forties", name: "Forties Field", country: "UK", kind: "field", lat: 57.8, lon: 1.7 },
    { id: "brent-ekofisk", name: "Ekofisk Field", country: "Norway", kind: "field", lat: 56.5, lon: 3.2 },
    { id: "brent-sullom", name: "Sullom Voe Terminal", country: "UK", kind: "terminal", lat: 60.46, lon: -1.31 },
    { id: "brent-ninian", name: "Ninian Field", country: "UK", kind: "field", lat: 60.8, lon: 1.4 },
    { id: "brent-statfjord", name: "Statfjord Field", country: "Norway", kind: "field", lat: 61.2, lon: 1.9 },
    { id: "brent-oseberg", name: "Oseberg Field", country: "Norway", kind: "field", lat: 60.5, lon: 2.8 },
    { id: "brent-troll", name: "Troll Field", country: "Norway", kind: "field", lat: 60.8, lon: 3.7 },
    { id: "brent-buzzard", name: "Buzzard Field", country: "UK", kind: "field", lat: 57.9, lon: 1.4 },
    { id: "brent-mongstad", name: "Mongstad Terminal", country: "Norway", kind: "terminal", lat: 60.81, lon: 5.03 },
  ],
  naturalGas: [
    { id: "gas-north-field", name: "North Field", country: "Qatar", kind: "field", lat: 26.0, lon: 51.8 },
    { id: "gas-south-pars", name: "South Pars", country: "Iran", kind: "field", lat: 27.0, lon: 52.6 },
    { id: "gas-marcellus", name: "Marcellus Basin", country: "United States", kind: "basin", lat: 41.0, lon: -77.7 },
    { id: "gas-yamal", name: "Yamal Core", country: "Russia", kind: "field", lat: 70.0, lon: 73.0 },
    { id: "gas-urengoy", name: "Urengoy Field", country: "Russia", kind: "field", lat: 65.9, lon: 78.4 },
    { id: "gas-haynesville", name: "Haynesville Basin", country: "United States", kind: "basin", lat: 32.5, lon: -93.7 },
    { id: "gas-bowen", name: "Bowen Basin", country: "Australia", kind: "basin", lat: -22.8, lon: 148.3 },
    { id: "gas-groningen", name: "Groningen Field", country: "Netherlands", kind: "field", lat: 53.3, lon: 6.7 },
    { id: "gas-hassi-rmel", name: "Hassi R'Mel", country: "Algeria", kind: "field", lat: 32.9, lon: 3.3 },
    { id: "gas-sakhalin", name: "Sakhalin LNG", country: "Russia", kind: "terminal", lat: 46.8, lon: 142.8 },
  ],
  aluminum: [
    { id: "alu-boke", name: "Boke Bauxite", country: "Guinea", kind: "mine", lat: 10.93, lon: -14.29 },
    { id: "alu-weipa", name: "Weipa Bauxite", country: "Australia", kind: "mine", lat: -12.62, lon: 141.88 },
    { id: "alu-huntly", name: "Huntly Bauxite", country: "Australia", kind: "mine", lat: -32.6, lon: 116.1 },
    { id: "alu-china-smelt", name: "Shandong Smelting Hub", country: "China", kind: "terminal", lat: 36.6, lon: 117.0 },
    { id: "alu-sangaredi", name: "Sangaredi Mine", country: "Guinea", kind: "mine", lat: 11.11, lon: -14.36 },
    { id: "alu-gove", name: "Gove Bauxite", country: "Australia", kind: "mine", lat: -12.18, lon: 136.78 },
    { id: "alu-juruti", name: "Juruti Mine", country: "Brazil", kind: "mine", lat: -2.15, lon: -56.09 },
    { id: "alu-trombetas", name: "Trombetas Mine", country: "Brazil", kind: "mine", lat: -1.6, lon: -56.4 },
    { id: "alu-pavlodar", name: "Pavlodar Smelter", country: "Kazakhstan", kind: "terminal", lat: 52.3, lon: 76.9 },
    { id: "alu-gladstone", name: "Gladstone Alumina Hub", country: "Australia", kind: "terminal", lat: -23.84, lon: 151.26 },
    { id: "alu-paragominas", name: "Paragominas Mine", country: "Brazil", kind: "mine", lat: -2.99, lon: -47.35 },
    { id: "alu-kindia", name: "Kindia Bauxite", country: "Guinea", kind: "mine", lat: 10.04, lon: -12.86 },
    { id: "alu-pinjarra", name: "Pinjarra Refinery", country: "Australia", kind: "terminal", lat: -32.63, lon: 115.87 },
    { id: "alu-yarwun", name: "Yarwun Refinery", country: "Australia", kind: "terminal", lat: -23.80, lon: 151.29 },
    { id: "alu-jebel-ali", name: "Jebel Ali Smelter", country: "UAE", kind: "terminal", lat: 24.98, lon: 55.07 },
    { id: "alu-shanxi", name: "Shanxi Alumina Hub", country: "China", kind: "terminal", lat: 37.87, lon: 112.55 },
    { id: "alu-samarco", name: "Samarco Bauxite", country: "Brazil", kind: "mine", lat: -20.24, lon: -43.42 },
    { id: "alu-dian-dian", name: "Dian-Dian Bauxite", country: "Guinea", kind: "mine", lat: 11.25, lon: -13.92 },
    { id: "alu-debrecen", name: "Ajka Legacy Bauxite", country: "Hungary", kind: "mine", lat: 47.10, lon: 17.56 },
    { id: "alu-kamsar", name: "Kamsar Export Terminal", country: "Guinea", kind: "terminal", lat: 10.66, lon: -14.62 },
    { id: "alu-portland", name: "Portland Aluminium", country: "Australia", kind: "terminal", lat: -38.35, lon: 141.61 },
    { id: "alu-iceland", name: "ISAL Smelter", country: "Iceland", kind: "terminal", lat: 63.89, lon: -22.55 },
  ],
  copper: [
    { id: "cu-escondida", name: "Escondida Mine", country: "Chile", kind: "mine", lat: -24.27, lon: -69.07 },
    { id: "cu-chuqui", name: "Chuquicamata Mine", country: "Chile", kind: "mine", lat: -22.31, lon: -68.93 },
    { id: "cu-grasberg", name: "Grasberg Mine", country: "Indonesia", kind: "mine", lat: -4.05, lon: 137.11 },
    { id: "cu-antamina", name: "Antamina Mine", country: "Peru", kind: "mine", lat: -9.53, lon: -77.05 },
    { id: "cu-collahuasi", name: "Collahuasi Mine", country: "Chile", kind: "mine", lat: -20.9, lon: -68.7 },
    { id: "cu-cerro-verde", name: "Cerro Verde", country: "Peru", kind: "mine", lat: -16.52, lon: -71.6 },
    { id: "cu-las-bambas", name: "Las Bambas", country: "Peru", kind: "mine", lat: -14.1, lon: -72.35 },
    { id: "cu-morenci", name: "Morenci Mine", country: "United States", kind: "mine", lat: 33.05, lon: -109.36 },
    { id: "cu-kansanshi", name: "Kansanshi Mine", country: "Zambia", kind: "mine", lat: -12.12, lon: 26.4 },
    { id: "cu-kamoa", name: "Kamoa-Kakula", country: "DR Congo", kind: "mine", lat: -10.72, lon: 24.5 },
    { id: "cu-cobre-panama", name: "Cobre Panama", country: "Panama", kind: "mine", lat: 8.53, lon: -80.96 },
    { id: "cu-quellaveco", name: "Quellaveco", country: "Peru", kind: "mine", lat: -16.62, lon: -70.56 },
    { id: "cu-bronces", name: "Los Bronces", country: "Chile", kind: "mine", lat: -33.13, lon: -70.18 },
    { id: "cu-radomiro", name: "Radomiro Tomic", country: "Chile", kind: "mine", lat: -22.32, lon: -68.64 },
    { id: "cu-pt-smelt", name: "Gresik Smelter", country: "Indonesia", kind: "terminal", lat: -7.15, lon: 112.65 },
    { id: "cu-daye", name: "Daye Smelter Hub", country: "China", kind: "terminal", lat: 30.10, lon: 114.97 },
    { id: "cu-el-teniente", name: "El Teniente", country: "Chile", kind: "mine", lat: -34.09, lon: -70.38 },
    { id: "cu-spence", name: "Spence Mine", country: "Chile", kind: "mine", lat: -22.75, lon: -69.40 },
    { id: "cu-los-pelambres", name: "Los Pelambres", country: "Chile", kind: "mine", lat: -31.72, lon: -70.50 },
    { id: "cu-kcc", name: "Kamoto Copper Company", country: "DR Congo", kind: "mine", lat: -10.73, lon: 25.46 },
    { id: "cu-bingham", name: "Bingham Canyon", country: "United States", kind: "mine", lat: 40.53, lon: -112.13 },
    { id: "cu-oak", name: "Oak Dam West", country: "Australia", kind: "mine", lat: -30.80, lon: 136.60 },
    { id: "cu-qingyuan", name: "Qingyuan Smelter Hub", country: "China", kind: "terminal", lat: 23.68, lon: 113.06 },
    { id: "cu-zhoushan", name: "Zhoushan Smelter", country: "China", kind: "terminal", lat: 30.01, lon: 122.11 },
  ],
  nickel: [
    { id: "ni-norilsk", name: "Norilsk Cluster", country: "Russia", kind: "mine", lat: 69.35, lon: 88.20 },
    { id: "ni-soro", name: "Sorowako", country: "Indonesia", kind: "mine", lat: -2.52, lon: 121.36 },
    { id: "ni-weda", name: "Weda Bay", country: "Indonesia", kind: "mine", lat: 0.62, lon: 128.29 },
    { id: "ni-sudbury", name: "Sudbury", country: "Canada", kind: "mine", lat: 46.49, lon: -81.01 },
    { id: "ni-thompson", name: "Thompson Belt", country: "Canada", kind: "mine", lat: 55.75, lon: -97.86 },
    { id: "ni-raglan", name: "Raglan Mine", country: "Canada", kind: "mine", lat: 61.99, lon: -75.65 },
    { id: "ni-koniambo", name: "Koniambo", country: "New Caledonia", kind: "mine", lat: -21.0, lon: 164.7 },
    { id: "ni-pt-obi", name: "Obi Processing", country: "Indonesia", kind: "terminal", lat: -1.58, lon: 127.8 },
    { id: "ni-caldag", name: "Caldag Project", country: "Turkey", kind: "mine", lat: 38.7, lon: 27.3 },
    { id: "ni-ambatovy", name: "Ambatovy", country: "Madagascar", kind: "mine", lat: -18.9, lon: 48.3 },
    { id: "ni-ravensthorpe", name: "Ravensthorpe", country: "Australia", kind: "mine", lat: -33.58, lon: 120.05 },
    { id: "ni-moa", name: "Moa Bay", country: "Cuba", kind: "mine", lat: 20.64, lon: -74.95 },
    { id: "ni-bahodopi", name: "Bahodopi Hub", country: "Indonesia", kind: "terminal", lat: -2.74, lon: 121.37 },
    { id: "ni-pomalaa", name: "Pomalaa", country: "Indonesia", kind: "mine", lat: -4.17, lon: 121.61 },
    { id: "ni-taganito", name: "Taganito", country: "Philippines", kind: "mine", lat: 9.53, lon: 125.80 },
    { id: "ni-goro", name: "Goro Mine", country: "New Caledonia", kind: "mine", lat: -22.31, lon: 166.73 },
    { id: "ni-murrin", name: "Murrin Murrin", country: "Australia", kind: "mine", lat: -28.79, lon: 121.89 },
    { id: "ni-kalgoorlie", name: "Kambalda Nickel Belt", country: "Australia", kind: "mine", lat: -30.77, lon: 121.47 },
    { id: "ni-pt-virtue", name: "Morowali HPAL", country: "Indonesia", kind: "terminal", lat: -2.95, lon: 122.14 },
    { id: "ni-rios", name: "Rio Tuba", country: "Philippines", kind: "mine", lat: 8.50, lon: 117.43 },
    { id: "ni-surigao", name: "Surigao Nickel Belt", country: "Philippines", kind: "mine", lat: 9.90, lon: 125.60 },
    { id: "ni-kola", name: "Kola MMC", country: "Russia", kind: "mine", lat: 68.05, lon: 33.09 },
    { id: "ni-pt-halmahera", name: "Halmahera Processing Hub", country: "Indonesia", kind: "terminal", lat: 0.75, lon: 127.85 },
    { id: "ni-ivoire", name: "Biankouma Nickel Project", country: "Cote d'Ivoire", kind: "mine", lat: 7.74, lon: -7.55 },
  ],
  zinc: [
    { id: "zn-red-dog", name: "Red Dog Mine", country: "United States", kind: "mine", lat: 68.07, lon: -162.86 },
    { id: "zn-rampura", name: "Rampura Agucha", country: "India", kind: "mine", lat: 25.95, lon: 74.73 },
    { id: "zn-mount-isa", name: "Mount Isa", country: "Australia", kind: "mine", lat: -20.73, lon: 139.49 },
    { id: "zn-dugald", name: "Dugald River", country: "Australia", kind: "mine", lat: -21.6, lon: 139.5 },
    { id: "zn-century", name: "Century District", country: "Australia", kind: "mine", lat: -18.9, lon: 138.7 },
    { id: "zn-mcarthur", name: "McArthur River", country: "Australia", kind: "mine", lat: -16.4, lon: 136.1 },
    { id: "zn-antamina", name: "Antamina Zn Circuit", country: "Peru", kind: "mine", lat: -9.53, lon: -77.05 },
    { id: "zn-teck-trail", name: "Trail Smelter", country: "Canada", kind: "terminal", lat: 49.1, lon: -117.7 },
    { id: "zn-zhairem", name: "Zhairem Hub", country: "Kazakhstan", kind: "mine", lat: 48.2, lon: 67.0 },
    { id: "zn-boliden", name: "Boliden Area", country: "Sweden", kind: "mine", lat: 64.86, lon: 20.38 },
    { id: "zn-navan", name: "Tara/Navan Zinc", country: "Ireland", kind: "mine", lat: 53.66, lon: -6.69 },
    { id: "zn-brucejack", name: "Brunswick Legacy", country: "Canada", kind: "mine", lat: 47.15, lon: -66.74 },
    { id: "zn-lisheen", name: "Lisheen Belt", country: "Ireland", kind: "mine", lat: 52.86, lon: -7.96 },
    { id: "zn-neves-corvo", name: "Neves-Corvo", country: "Portugal", kind: "mine", lat: 37.57, lon: -7.98 },
    { id: "zn-skorpion", name: "Skorpion Zinc", country: "Namibia", kind: "mine", lat: -27.96, lon: 16.95 },
    { id: "zn-melbourne", name: "Port Pirie Smelter", country: "Australia", kind: "terminal", lat: -33.18, lon: 138.02 },
    { id: "zn-penoles", name: "Torreon Met-Mex", country: "Mexico", kind: "terminal", lat: 25.54, lon: -103.45 },
    { id: "zn-yunnan", name: "Yunnan Zinc Smelting", country: "China", kind: "terminal", lat: 25.04, lon: 102.72 },
  ],
  lead: [
    { id: "pb-cannington", name: "Cannington", country: "Australia", kind: "mine", lat: -21.9, lon: 140.9 },
    { id: "pb-mtisa", name: "Mount Isa Lead", country: "Australia", kind: "mine", lat: -20.73, lon: 139.49 },
    { id: "pb-yunnan", name: "Yunnan Lead Hub", country: "China", kind: "belt", lat: 25.0, lon: 102.7 },
    { id: "pb-zambia", name: "Kabwe Area", country: "Zambia", kind: "mine", lat: -14.45, lon: 28.45 },
    { id: "pb-broken-hill", name: "Broken Hill", country: "Australia", kind: "mine", lat: -31.95, lon: 141.45 },
    { id: "pb-hela", name: "Huludao Smelter Hub", country: "China", kind: "terminal", lat: 40.71, lon: 120.84 },
    { id: "pb-missouri", name: "SE Missouri Belt", country: "United States", kind: "belt", lat: 37.6, lon: -90.5 },
    { id: "pb-navan", name: "Navan District", country: "Ireland", kind: "mine", lat: 53.65, lon: -6.68 },
    { id: "pb-torreon", name: "Torreon Smelting Hub", country: "Mexico", kind: "terminal", lat: 25.54, lon: -103.45 },
    { id: "pb-olkusz", name: "Olkusz District", country: "Poland", kind: "mine", lat: 50.28, lon: 19.57 },
    { id: "pb-teena", name: "Teena Deposit", country: "Australia", kind: "mine", lat: -16.58, lon: 136.52 },
    { id: "pb-pasco", name: "Cerro de Pasco", country: "Peru", kind: "mine", lat: -10.68, lon: -76.25 },
    { id: "pb-mcarthur", name: "McArthur Lead-Zinc", country: "Australia", kind: "mine", lat: -16.4, lon: 136.1 },
    { id: "pb-viburnum", name: "Viburnum Trend", country: "United States", kind: "mine", lat: 37.73, lon: -90.67 },
    { id: "pb-kidd", name: "Kidd Creek", country: "Canada", kind: "mine", lat: 48.49, lon: -81.33 },
    { id: "pb-trail", name: "Trail Lead Smelter", country: "Canada", kind: "terminal", lat: 49.1, lon: -117.7 },
    { id: "pb-xuzhou", name: "Xuzhou Lead Smelting", country: "China", kind: "terminal", lat: 34.2, lon: 117.2 },
    { id: "pb-potosi", name: "Potosi Pb-Ag Belt", country: "Bolivia", kind: "mine", lat: -19.6, lon: -65.75 },
  ],
  tin: [
    { id: "sn-bangka", name: "Bangka Tin Belt", country: "Indonesia", kind: "belt", lat: -2.2, lon: 106.1 },
    { id: "sn-san-rafael", name: "San Rafael Mine", country: "Peru", kind: "mine", lat: -14.2, lon: -70.3 },
    { id: "sn-renison", name: "Renison Mine", country: "Australia", kind: "mine", lat: -41.8, lon: 145.5 },
    { id: "sn-yunnan", name: "Yunnan Tin Hub", country: "China", kind: "belt", lat: 23.4, lon: 103.4 },
    { id: "sn-bisie", name: "Bisie Mine", country: "DR Congo", kind: "mine", lat: -1.53, lon: 28.75 },
    { id: "sn-hemlo", name: "Minsur Processing Hub", country: "Peru", kind: "terminal", lat: -15.84, lon: -70.02 },
    { id: "sn-gejiu", name: "Gejiu Hub", country: "China", kind: "terminal", lat: 23.36, lon: 103.16 },
    { id: "sn-huayuan", name: "Huayuan Belt", country: "China", kind: "belt", lat: 28.58, lon: 109.48 },
    { id: "sn-luena", name: "Luena District", country: "Angola", kind: "mine", lat: -11.78, lon: 19.91 },
    { id: "sn-phuket", name: "Andaman Tin Legacy", country: "Thailand", kind: "belt", lat: 8.0, lon: 98.3 },
    { id: "sn-alphamin", name: "Mpama North (Alphamin)", country: "DR Congo", kind: "mine", lat: -1.51, lon: 28.76 },
    { id: "sn-bolivia-llallagua", name: "Llallagua District", country: "Bolivia", kind: "mine", lat: -18.42, lon: -66.58 },
    { id: "sn-heemskirk", name: "Heemskirk Project", country: "Australia", kind: "mine", lat: -41.9, lon: 145.3 },
    { id: "sn-phonsack", name: "Phonsack Belt", country: "Laos", kind: "mine", lat: 19.5, lon: 103.5 },
    { id: "sn-myanmar-wa", name: "Wa State Tin Belt", country: "Myanmar", kind: "mine", lat: 22.5, lon: 99.1 },
    { id: "sn-rwanda", name: "Rwanda Tin Corridor", country: "Rwanda", kind: "mine", lat: -1.98, lon: 29.62 },
    { id: "sn-pt-timah", name: "Muntok Processing Hub", country: "Indonesia", kind: "terminal", lat: -2.06, lon: 105.17 },
    { id: "sn-jiangxi-smelt", name: "Jiangxi Tin Smelting", country: "China", kind: "terminal", lat: 28.68, lon: 115.90 },
  ],
  cobalt: [
    { id: "co-tenke", name: "Tenke Fungurume", country: "DR Congo", kind: "mine", lat: -10.61, lon: 26.39 },
    { id: "co-kolwezi", name: "Kolwezi Cluster", country: "DR Congo", kind: "mine", lat: -10.72, lon: 25.47 },
    { id: "co-katanga", name: "Katanga Belt", country: "DR Congo", kind: "belt", lat: -11.3, lon: 27.5 },
    { id: "co-morowali", name: "Morowali Processing", country: "Indonesia", kind: "terminal", lat: -2.8, lon: 122.1 },
    { id: "co-mutanda", name: "Mutanda Mine", country: "DR Congo", kind: "mine", lat: -10.67, lon: 27.5 },
    { id: "co-kamoto", name: "Kamoto Complex", country: "DR Congo", kind: "mine", lat: -10.73, lon: 25.46 },
    { id: "co-kisanfu", name: "Kisanfu Project", country: "DR Congo", kind: "mine", lat: -10.72, lon: 25.18 },
    { id: "co-weda-refine", name: "Weda Bay Processing", country: "Indonesia", kind: "terminal", lat: 0.62, lon: 128.29 },
    { id: "co-ambatovy", name: "Ambatovy Co-byproduct", country: "Madagascar", kind: "mine", lat: -18.9, lon: 48.3 },
    { id: "co-ramu", name: "Ramu Ni-Co", country: "Papua New Guinea", kind: "mine", lat: -5.2, lon: 145.8 },
    { id: "co-etoile", name: "Etoile Mine", country: "DR Congo", kind: "mine", lat: -11.61, lon: 27.47 },
    { id: "co-deziwa", name: "Deziwa Project", country: "DR Congo", kind: "mine", lat: -10.95, lon: 25.90 },
    { id: "co-mopani", name: "Mopani Belt", country: "Zambia", kind: "mine", lat: -12.55, lon: 27.85 },
    { id: "co-finch", name: "Nikkelverk Refinery", country: "Norway", kind: "terminal", lat: 58.16, lon: 8.00 },
    { id: "co-sorowako-refine", name: "Sorowako Processing", country: "Indonesia", kind: "terminal", lat: -2.52, lon: 121.36 },
    { id: "co-chambishi", name: "Chambishi Refinery", country: "Zambia", kind: "terminal", lat: -12.66, lon: 28.00 },
    { id: "co-kambove", name: "Kambove District", country: "DR Congo", kind: "mine", lat: -10.88, lon: 26.60 },
    { id: "co-idaho-cobalt", name: "Idaho Cobalt Belt", country: "United States", kind: "mine", lat: 44.93, lon: -114.10 },
  ],
  lithium: [
    { id: "li-atacama", name: "Salar de Atacama", country: "Chile", kind: "mine", lat: -23.3, lon: -68.2 },
    { id: "li-greenbushes", name: "Greenbushes Mine", country: "Australia", kind: "mine", lat: -33.86, lon: 116.06 },
    { id: "li-pilgangoora", name: "Pilgangoora", country: "Australia", kind: "mine", lat: -21.3, lon: 118.6 },
    { id: "li-uyuni", name: "Salar de Uyuni", country: "Bolivia", kind: "mine", lat: -20.1, lon: -67.5 },
    { id: "li-hombre-muerto", name: "Salar del Hombre Muerto", country: "Argentina", kind: "mine", lat: -25.4, lon: -67.3 },
    { id: "li-olaroz", name: "Olaroz", country: "Argentina", kind: "mine", lat: -23.7, lon: -66.7 },
    { id: "li-whabouchi", name: "Whabouchi", country: "Canada", kind: "mine", lat: 54.58, lon: -74.22 },
    { id: "li-manono", name: "Manono Project", country: "DR Congo", kind: "mine", lat: -7.3, lon: 27.4 },
    { id: "li-jiangxi", name: "Jiangxi Refining Hub", country: "China", kind: "terminal", lat: 27.8, lon: 114.4 },
    { id: "li-qinghai", name: "Qinghai Salt Lake", country: "China", kind: "mine", lat: 36.6, lon: 95.6 },
    { id: "li-thacker-pass", name: "Thacker Pass", country: "United States", kind: "mine", lat: 41.71, lon: -118.06 },
    { id: "li-kings-mountain", name: "Kings Mountain", country: "United States", kind: "mine", lat: 35.20, lon: -81.34 },
    { id: "li-sig", name: "Sal de Vida", country: "Argentina", kind: "mine", lat: -25.67, lon: -67.23 },
    { id: "li-goulamina", name: "Goulamina", country: "Mali", kind: "mine", lat: -11.39, lon: -7.28 },
    { id: "li-zhabuye", name: "Zhabuye Salt Lake", country: "China", kind: "mine", lat: 31.8, lon: 84.0 },
    { id: "li-kwinana", name: "Kwinana Refinery", country: "Australia", kind: "terminal", lat: -32.20, lon: 115.76 },
    { id: "li-mt-marion", name: "Mt Marion", country: "Australia", kind: "mine", lat: -29.95, lon: 121.30 },
    { id: "li-wodgina", name: "Wodgina", country: "Australia", kind: "mine", lat: -21.23, lon: 118.69 },
    { id: "li-finniss", name: "Finniss", country: "Australia", kind: "mine", lat: -13.74, lon: 131.08 },
    { id: "li-cauchari", name: "Cauchari-Olaroz", country: "Argentina", kind: "mine", lat: -23.6, lon: -66.8 },
    { id: "li-rincon", name: "Salar del Rincon", country: "Argentina", kind: "mine", lat: -25.2, lon: -67.6 },
    { id: "li-arcadia", name: "Arcadia", country: "Zimbabwe", kind: "mine", lat: -20.42, lon: 31.95 },
    { id: "li-bikita", name: "Bikita", country: "Zimbabwe", kind: "mine", lat: -20.15, lon: 31.70 },
    { id: "li-jadar", name: "Jadar (project)", country: "Serbia", kind: "mine", lat: 44.55, lon: 19.23 },
    { id: "li-nemaska", name: "Nemaska Whabouchi Corridor", country: "Canada", kind: "mine", lat: 53.95, lon: -74.00 },
    { id: "li-tres-quebradas", name: "Tres Quebradas", country: "Argentina", kind: "mine", lat: -26.0, lon: -68.0 },
  ],
  gallium: [
    { id: "ga-guangxi", name: "Guangxi Processing Hub", country: "China", kind: "terminal", lat: 23.8, lon: 108.3 },
    { id: "ga-henan", name: "Henan Refining Hub", country: "China", kind: "terminal", lat: 34.7, lon: 113.6 },
    { id: "ga-shandong", name: "Shandong Processing Hub", country: "China", kind: "terminal", lat: 36.7, lon: 117.0 },
    { id: "ga-germany", name: "German Recycle Hub", country: "Germany", kind: "terminal", lat: 51.2, lon: 6.8 },
    { id: "ga-hunan", name: "Hunan Processing Hub", country: "China", kind: "terminal", lat: 28.2, lon: 112.9 },
    { id: "ga-guizhou", name: "Guizhou Refining", country: "China", kind: "terminal", lat: 26.6, lon: 106.7 },
    { id: "ga-japan", name: "Kyushu Epitaxy Hub", country: "Japan", kind: "terminal", lat: 33.6, lon: 130.4 },
    { id: "ga-korea", name: "Incheon Semiconductor Materials", country: "South Korea", kind: "terminal", lat: 37.45, lon: 126.7 },
    { id: "ga-usa", name: "Utah Recycle Hub", country: "United States", kind: "terminal", lat: 40.7, lon: -111.9 },
    { id: "ga-belgium", name: "Antwerp Specialty Metals", country: "Belgium", kind: "terminal", lat: 51.2, lon: 4.4 },
    { id: "ga-henan-bauxite", name: "Henan Bauxite Belt", country: "China", kind: "mine", lat: 34.8, lon: 112.7 },
    { id: "ga-shanxi-bauxite", name: "Shanxi Bauxite Belt", country: "China", kind: "mine", lat: 36.2, lon: 111.5 },
    { id: "ga-guizhou-bauxite", name: "Guizhou Bauxite Belt", country: "China", kind: "mine", lat: 26.9, lon: 106.4 },
    { id: "ga-jamaica-bauxite", name: "Jamaica Bauxite Feed", country: "Jamaica", kind: "mine", lat: 18.1, lon: -77.3 },
    { id: "ga-australia-bauxite", name: "Queensland Bauxite Feed", country: "Australia", kind: "mine", lat: -12.6, lon: 141.9 },
  ],
  germanium: [
    { id: "ge-yunnan", name: "Yunnan Hub", country: "China", kind: "terminal", lat: 24.9, lon: 102.8 },
    { id: "ge-innermongolia", name: "Inner Mongolia Hub", country: "China", kind: "terminal", lat: 40.8, lon: 111.7 },
    { id: "ge-belgium", name: "Belgium Refining", country: "Belgium", kind: "terminal", lat: 51.2, lon: 4.4 },
    { id: "ge-canada", name: "Trail Refinery", country: "Canada", kind: "terminal", lat: 49.1, lon: -117.7 },
    { id: "ge-hunan", name: "Hunan Ge Hub", country: "China", kind: "terminal", lat: 28.2, lon: 112.9 },
    { id: "ge-jiangsu", name: "Jiangsu Optical Materials", country: "China", kind: "terminal", lat: 32.1, lon: 118.8 },
    { id: "ge-usa", name: "Oklahoma Ge Processing", country: "United States", kind: "terminal", lat: 36.1, lon: -95.9 },
    { id: "ge-russia", name: "Far East Ge Hub", country: "Russia", kind: "terminal", lat: 43.1, lon: 131.9 },
    { id: "ge-korea", name: "Gumi Electronics Hub", country: "South Korea", kind: "terminal", lat: 36.1, lon: 128.3 },
    { id: "ge-japan", name: "Ibaraki Ge Materials", country: "Japan", kind: "terminal", lat: 36.3, lon: 140.5 },
    { id: "ge-yunnan-zn-pb", name: "Yunnan Zn-Pb Belt", country: "China", kind: "mine", lat: 25.0, lon: 103.0 },
    { id: "ge-innermongolia-zn", name: "Inner Mongolia Zn Belt", country: "China", kind: "mine", lat: 41.2, lon: 111.5 },
    { id: "ge-kidd-creek", name: "Kidd Creek Zn-Cu Belt", country: "Canada", kind: "mine", lat: 48.49, lon: -81.33 },
    { id: "ge-red-dog-source", name: "Red Dog Zn Feed", country: "United States", kind: "mine", lat: 68.07, lon: -162.86 },
    { id: "ge-russia-zinc", name: "Siberian Zn Belt", country: "Russia", kind: "mine", lat: 54.7, lon: 90.5 },
  ],
  gold: [
    { id: "au-muruntau", name: "Muruntau Mine", country: "Uzbekistan", kind: "mine", lat: 41.56, lon: 64.59 },
    { id: "au-carlin", name: "Carlin Trend", country: "United States", kind: "mine", lat: 40.95, lon: -116.3 },
    { id: "au-olimpiada", name: "Olimpiada Mine", country: "Russia", kind: "mine", lat: 60.6, lon: 95.2 },
    { id: "au-boddington", name: "Boddington Mine", country: "Australia", kind: "mine", lat: -32.8, lon: 116.4 },
    { id: "au-cortez", name: "Cortez Complex", country: "United States", kind: "mine", lat: 40.2, lon: -116.7 },
    { id: "au-kibali", name: "Kibali Mine", country: "DR Congo", kind: "mine", lat: 3.2, lon: 30.7 },
    { id: "au-lihir", name: "Lihir Mine", country: "Papua New Guinea", kind: "mine", lat: -3.13, lon: 152.64 },
    { id: "au-pueblo-viejo", name: "Pueblo Viejo", country: "Dominican Republic", kind: "mine", lat: 18.9, lon: -70.2 },
    { id: "au-grasberg", name: "Grasberg Au-Cu", country: "Indonesia", kind: "mine", lat: -4.05, lon: 137.11 },
    { id: "au-kalgoorlie", name: "Kalgoorlie Super Pit", country: "Australia", kind: "mine", lat: -30.78, lon: 121.51 },
    { id: "au-cadet", name: "Cadia Valley", country: "Australia", kind: "mine", lat: -33.45, lon: 149.07 },
    { id: "au-donlin", name: "Donlin Creek", country: "United States", kind: "mine", lat: 62.0, lon: -158.1 },
    { id: "au-loulo", name: "Loulo-Gounkoto", country: "Mali", kind: "mine", lat: 14.9, lon: -11.3 },
    { id: "au-detour", name: "Detour Lake", country: "Canada", kind: "mine", lat: 50.8, lon: -79.7 },
    { id: "au-yanacocha", name: "Yanacocha", country: "Peru", kind: "mine", lat: -6.97, lon: -78.50 },
    { id: "au-olympic-dam", name: "Olympic Dam Au-Cu", country: "Australia", kind: "mine", lat: -30.44, lon: 136.89 },
    { id: "au-sukari", name: "Sukari Mine", country: "Egypt", kind: "mine", lat: 24.95, lon: 34.73 },
    { id: "au-porgera", name: "Porgera", country: "Papua New Guinea", kind: "mine", lat: -5.47, lon: 143.05 },
    { id: "au-agi-darnley", name: "Fosterville", country: "Australia", kind: "mine", lat: -36.73, lon: 144.84 },
    { id: "au-assa-obia", name: "Obuasi", country: "Ghana", kind: "mine", lat: 6.20, lon: -1.68 },
    { id: "au-kumtor", name: "Kumtor", country: "Kyrgyzstan", kind: "mine", lat: 41.86, lon: 78.18 },
    { id: "au-canadian-malari", name: "Canadian Malartic", country: "Canada", kind: "mine", lat: 48.13, lon: -78.13 },
    { id: "au-southdeep", name: "South Deep", country: "South Africa", kind: "mine", lat: -26.41, lon: 27.74 },
    { id: "au-tasiast", name: "Tasiast", country: "Mauritania", kind: "mine", lat: 20.50, lon: -15.49 },
  ],
  silver: [
    { id: "ag-fresnillo", name: "Fresnillo District", country: "Mexico", kind: "mine", lat: 23.2, lon: -102.9 },
    { id: "ag-penasquito", name: "Penasquito Mine", country: "Mexico", kind: "mine", lat: 24.63, lon: -101.72 },
    { id: "ag-cannington", name: "Cannington Ag-Pb", country: "Australia", kind: "mine", lat: -21.9, lon: 140.9 },
    { id: "ag-cerro-rico", name: "Potosi Belt", country: "Bolivia", kind: "mine", lat: -19.6, lon: -65.75 },
    { id: "ag-saucito", name: "Saucito Mine", country: "Mexico", kind: "mine", lat: 23.33, lon: -102.9 },
    { id: "ag-san-julian", name: "San Julian", country: "Mexico", kind: "mine", lat: 26.0, lon: -106.0 },
    { id: "ag-uchucchacua", name: "Uchucchacua", country: "Peru", kind: "mine", lat: -10.7, lon: -76.7 },
    { id: "ag-manantial", name: "Manantial Espejo", country: "Argentina", kind: "mine", lat: -48.7, lon: -70.3 },
    { id: "ag-kghm", name: "KGHM Legnica-Glogow", country: "Poland", kind: "mine", lat: 51.2, lon: 16.2 },
    { id: "ag-juanicipio", name: "Juanicipio", country: "Mexico", kind: "mine", lat: 23.4, lon: -102.8 },
    { id: "ag-escobal", name: "Escobal", country: "Guatemala", kind: "mine", lat: 14.05, lon: -90.37 },
    { id: "ag-san-cristobal", name: "San Cristobal", country: "Bolivia", kind: "mine", lat: -21.21, lon: -67.24 },
    { id: "ag-pirquitas", name: "Pirquitas-Chinchillas", country: "Argentina", kind: "mine", lat: -22.3, lon: -66.5 },
    { id: "ag-polkowice", name: "Polkowice-Sieroszowice", country: "Poland", kind: "mine", lat: 51.51, lon: 16.11 },
    { id: "ag-caylloma", name: "Caylloma", country: "Peru", kind: "mine", lat: -15.2, lon: -71.8 },
    { id: "ag-zgounder", name: "Zgounder", country: "Morocco", kind: "mine", lat: 30.6, lon: -8.3 },
    { id: "ag-keno", name: "Keno Hill", country: "Canada", kind: "mine", lat: 63.9, lon: -135.3 },
    { id: "ag-guanacevi", name: "Guanacevi", country: "Mexico", kind: "mine", lat: 25.93, lon: -106.13 },
  ],
};
