import { commodityVesselPoints, vesselWatchZones, type CommodityVesselPoint, type CommodityVesselType } from "@/lib/commodityVessels";

export const vesselTypeLabels: Record<CommodityVesselType, string> = {
  crude_tanker: "Crude Tanker",
  product_tanker: "Product Tanker",
  lng_tanker: "LNG Tanker",
  bulk_carrier: "Bulk Carrier",
  container_ship: "Container Ship",
  general_cargo: "General Cargo",
};

export const vesselTypeColors: Record<CommodityVesselType, string> = {
  crude_tanker: "#c45f18",
  product_tanker: "#d78738",
  lng_tanker: "#007fa3",
  bulk_carrier: "#0f5f6f",
  container_ship: "#263f7f",
  general_cargo: "#5b6472",
};

const additionalGlobalVesselSamples: CommodityVesselPoint[] = [
  {
    id: "gv-crude-atlantic-1",
    name: "Atlantic Juniper",
    mmsi: "538009401",
    imo: "9842301",
    vesselType: "crude_tanker",
    lat: 35.9,
    lon: -10.8,
    speedKnots: 12.4,
    course: 84,
    destination: "Rotterdam",
    eta: "2026-05-12 18:20 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "West Africa / Atlantic -> Northwest Europe refining hub",
    commodityHint: "Crude tanker lane; cargo type needs cargo intelligence confirmation",
    relevance: "medium",
    source: "sample_ais_ready",
  },
  {
    id: "gv-crude-usg-1",
    name: "Bayou Meridian",
    mmsi: "367884210",
    imo: "9817745",
    vesselType: "crude_tanker",
    lat: 28.6,
    lon: -94.5,
    speedKnots: 9.8,
    course: 117,
    destination: "Corpus Christi",
    eta: "2026-05-09 06:40 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "US Gulf crude export / refinery corridor",
    commodityHint: "Crude or condensate corridor watch",
    relevance: "high",
    source: "sample_ais_ready",
  },
  {
    id: "gv-product-med-1",
    name: "Aegean Product",
    mmsi: "241990000",
    imo: "9768124",
    vesselType: "product_tanker",
    lat: 35.4,
    lon: 19.2,
    speedKnots: 10.7,
    course: 295,
    destination: "Piraeus",
    eta: "2026-05-10 11:10 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "Mediterranean refined product shuttle",
    commodityHint: "Refined products; AIS cannot identify exact grade",
    relevance: "watch",
    source: "sample_ais_ready",
  },
  {
    id: "gv-lng-aus-1",
    name: "Pilbara LNG",
    mmsi: "503880123",
    imo: "9872018",
    vesselType: "lng_tanker",
    lat: -19.3,
    lon: 116.7,
    speedKnots: 15.1,
    course: 21,
    destination: "Incheon",
    eta: "2026-05-17 02:15 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "Northwest Australia -> Northeast Asia LNG corridor",
    commodityHint: "LNG tanker; commodity type confidence is high, buyer/cargo terms require paid data",
    relevance: "high",
    source: "sample_ais_ready",
  },
  {
    id: "gv-lng-atlantic-1",
    name: "Sabine Crystal",
    mmsi: "368118930",
    imo: "9865221",
    vesselType: "lng_tanker",
    lat: 25.2,
    lon: -81.8,
    speedKnots: 13.9,
    course: 73,
    destination: "Zeebrugge",
    eta: "2026-05-19 20:30 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "US LNG -> Atlantic Basin",
    commodityHint: "LNG cargo lane; destination can change after reload/diversion",
    relevance: "medium",
    source: "sample_ais_ready",
  },
  {
    id: "gv-bulk-iron-aus",
    name: "Pilbara Cape",
    mmsi: "503771290",
    imo: "9712842",
    vesselType: "bulk_carrier",
    lat: -20.5,
    lon: 118.6,
    speedKnots: 11.9,
    course: 12,
    destination: "Qingdao",
    eta: "2026-05-20 09:00 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "Western Australia iron ore -> China steel chain",
    commodityHint: "Iron ore / dry bulk lane inference",
    relevance: "high",
    source: "sample_ais_ready",
  },
  {
    id: "gv-bulk-blacksea",
    name: "Black Sea Grain",
    mmsi: "271044610",
    imo: "9658826",
    vesselType: "bulk_carrier",
    lat: 41.2,
    lon: 30.7,
    speedKnots: 8.5,
    course: 205,
    destination: "Alexandria",
    eta: "2026-05-11 14:30 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "Black Sea -> Mediterranean grain corridor",
    commodityHint: "Wheat / corn export lane inference",
    relevance: "high",
    source: "sample_ais_ready",
  },
  {
    id: "gv-bulk-rio-plate",
    name: "Plate Harvest",
    mmsi: "710006210",
    imo: "9741192",
    vesselType: "bulk_carrier",
    lat: -35.1,
    lon: -56.2,
    speedKnots: 10.1,
    course: 92,
    destination: "Southeast Asia",
    eta: "2026-06-09 22:00 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "Argentina / Uruguay grain ports -> Asia",
    commodityHint: "Soybean meal / corn / wheat dry bulk lane",
    relevance: "medium",
    source: "sample_ais_ready",
  },
  {
    id: "gv-bulk-safrica",
    name: "Cape Manganese",
    mmsi: "601112330",
    imo: "9720158",
    vesselType: "bulk_carrier",
    lat: -33.7,
    lon: 18.1,
    speedKnots: 12.7,
    course: 108,
    destination: "Singapore",
    eta: "2026-05-27 16:00 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "South Africa minerals -> Asia",
    commodityHint: "Ore / manganese / coal dry bulk inference",
    relevance: "medium",
    source: "sample_ais_ready",
  },
  {
    id: "gv-container-pacific",
    name: "Pacific Loom",
    mmsi: "563880241",
    imo: "9891123",
    vesselType: "container_ship",
    lat: 34.1,
    lon: 150.3,
    speedKnots: 18.4,
    course: 72,
    destination: "Los Angeles",
    eta: "2026-05-18 08:45 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "Trans-Pacific container corridor",
    commodityHint: "Containerized goods; commodity identity needs bill-of-lading data",
    relevance: "watch",
    source: "sample_ais_ready",
  },
  {
    id: "gv-container-europe",
    name: "North Sea Relay",
    mmsi: "244980000",
    imo: "9788841",
    vesselType: "container_ship",
    lat: 51.9,
    lon: 3.6,
    speedKnots: 13.3,
    course: 54,
    destination: "Hamburg",
    eta: "2026-05-09 15:10 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "Rotterdam / Hamburg feeder corridor",
    commodityHint: "Containerized industrial inputs and consumer goods",
    relevance: "watch",
    source: "sample_ais_ready",
  },
  {
    id: "gv-general-indian",
    name: "Arabian Gear",
    mmsi: "419330120",
    imo: "9627334",
    vesselType: "general_cargo",
    lat: 18.8,
    lon: 67.5,
    speedKnots: 9.2,
    course: 119,
    destination: "Mumbai",
    eta: "2026-05-13 03:50 UTC",
    observedAt: "Sample AIS scenario",
    routeHint: "Arabian Sea industrial cargo corridor",
    commodityHint: "General cargo; exact cargo requires customs or bill-of-lading data",
    relevance: "watch",
    source: "sample_ais_ready",
  },
];

export const globalVesselSamples: CommodityVesselPoint[] = [...commodityVesselPoints, ...additionalGlobalVesselSamples];

export const vesselMapSourceSummary = {
  mode: "Sample / AIS-ready",
  coverage: "非全球即時全量；目前只展示可互動架構與船型、航線、目的港、ETA 欄位。",
  liveRequirement: "要顯示全世界目前船舶點位，需要接入 Spire、MarineTraffic、VesselFinder、AISHub 或同級 AIS provider。",
  updateFrequency: "目前 sample 不會自動更新；接入 live AIS 後可設定 1-15 分鐘輪詢或串流更新，依供應商方案而定。",
};

export { vesselWatchZones };
